spring.application.name=admin
spring.datasource.url=jdbc:postgresql://postgresql:5432/mitsuru_home
spring.datasource.username=mitsuru
spring.datasource.password=nachan
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
