# build stage 
FROM gradle:8-jdk21 AS build
WORKDIR /app
COPY build.gradle settings.gradle ./
COPY src ./src
# ignore test stage in this step for build performance
RUN gradle bootJar -x test

#Run stage
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/build/libs/*.jar app.jar
EXPOSE  8080
ENTRYPOINT [ "java", "-jar", "app.jar" ]
